version: "3.8"

services:
  api:
    image: alexscifier/neonlink_api
    volumes:
      - ./server/db/bookmarks.sqlite:/usr/src/neonlink/db/bookmarks.sqlite
  app:
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"
    image: alexscifier/neonlink_app
