version: "3.8"

services:
  neonlink:
    image: alexscifier/neonlink
    container_name: neonlink
    volumes:
      - ./data:/app/data
      - ./background:/app/public/static/media/background
    environment:
      - FASTIFY_PLUGIN_TIMEOUT=10000 # Set to 0 if ERR_AVVIO_PLUGIN_TIMEOUT error occurs.
      - UID=1000
      - GID=1000
      - UMASK=22
    restart: unless-stopped
    ports:
      - "80:3333"
