version: "3.8"

services:
  neonlink:
    image: alexscifier/neonlink
    container_name: neonlink
    # user: 1000:1000 # optional
    volumes:
      - ./data:/app/data
      - ./background:/app/public/static/media/background
    restart: unless-stopped
    environment:
      FASTIFY_PLUGIN_TIMEOUT: 120000 # optional: change to 0 if AVV_ERR_READY TIMEOUT error is occured
    ports:
      - "80:3333"
